apiVersion: v1
kind: Service
metadata:
  name: nodeport
  labels:
    svc: nodeport
spec:
  type: NodePort
  selector:
    app: flask
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30800