name: flask-cicd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: tabarak23/flask-k8s-app
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install testing dependencies
        run: |
          pip install coverage pytest pytest-cov flake8 black

      - name: Setup PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Autoformat tests
        run: black test_tests.py

      - name: Lint code
        run: flake8 .

      - name: Run tests and collect coverage
        run: |
          pytest --junitxml=pytest-report.xml
          coverage run -m pytest
          coverage xml -o coverage.xml

      - name: Install kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: creating kind cluster
        run: kind create cluster --name ci-cluster

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: image build
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: image to kind
        run: kind load docker-image $IMAGE_NAME:$IMAGE_TAG --name ci-cluster

      - name: tagging 
        run: sed -i "s|TAG|${IMAGE_TAG}|g" k8s/dep.yaml

      - name: k8s apply
        run: kubectl apply -f k8s/

      - name: rolling 
        run: kubectl rollout status deployment/flas-app --timeout=60s

      - name: Test Flask app on kind cluster
        run: |
          kubectl port-forward svc/nodeport 5000:5000 &
          sleep 5
          curl http://localhost:5000/
