name: flask-cicd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: cloning of code
        uses: actions/checkout@v4
      
      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  linting-testing:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
      - name: Install testing dependencies
        run: |
          pip install coverage pytest pytest-cov
      - name: setting up path 
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
      - name: autoformatter
        run: |
          black test_tests.py

      - name: linting with flake
        run: |
          flake8 .
      - name: Run Pytest with Reports
        run: |
          pytest --junitxml=pytest-report.xml
          coverage run -m pytest
          coverage xml -o coverage.xml
     